import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import AuthProvider from "./provider/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <AuthProvider>
          <Navbar />
          <div className="flex min-h-[calc(100vh-66px)] justify-center items-center">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
